% SCRIPT FOR USING SIMULINK

clear
clc
close all


Delta_a = 0;
Delta_e = 0;
Delta_r = 0;
Delta_x = 0;

open('Testing.slx'); %For opening if you want, it is optional
sim('Testing.slx');   % For running the simulink model by using the 'sym' command




%% HOW TO GET DATA FROM SIMULINK INTO MATLAB, 3 WAYS!!

%First one : Using output blocks
%Second one: ToWorkspace sink blocks
%Third one: Logging out a signal

%Extract the data generated by the simulink model through an output block
% When you run the simulink a yout signal will appear in the workspace

x_signal = yout.getElement('theta'); % theta is the name of the output signal vector
t= x_signal.values.time;
Theta = x_signal.values.Data;

%we can plot them!
figure
plot(t,Theta)
xlabel('time (seconds)')
ylabel('\theta (radians)')
grid on
title('Data generated by the Simulink model')



% Imaging you are getting a vector from the output (by using a mux in Simulink before the 
%output)
x_signal  = yout.getElement('x');   % x is the name of the output signal vector
t         = x_signal.values.time;
Theta     = x_signal.values.Data(:,1);
Theta_dot = x_signal.values.Data(:,2);







% For getting out data from simulink you can use a sink block called "To Workspace" 
% It allows you to pass Timeseries, Structure with time, Structure, array
% Supossing that this signal is called "simX", and the type is Timeseries
% after running it will be in the workspace

t         = simX.Time;
theta     = simX.Data(:,1);
theta_dot = simX.Data(:,2);

% If the signal instead in the block ToWorkspace is a structure with time,
% then 

t         = simX.time;
theta     = simX.signals.values(:,1);
theta_dot = simX.signals.values(:,2);

% The final method is called signal logging
% It is important to name the signal
% After that, right click on the signal and properties and check "Log
% signal data". A "wifi" icon should appear next to the signal

% If you click then in configuration parameters "Data import/export"
% If you run the model a variable called logsout will appear in the
% workspace



x_signal = logsout.getElement('theta'); % theta is the name of the output signal vector
t= x_signal.values.time;
Theta = x_signal.values.Data;





%% HOW TO PUT DATA INTO SIMULINK FROM MATLAB

%1st method. With a block in sources called "From Workspace". The input
%signal is going to be called 'simT'. 'simT' has now to be a vector with
%two columns, the first one the time and the second one the value.

tFinal = 10;
t_in = linspace(0, tFinal, 100);
T_in = zeros(size(t_in));

for k=1:length(t_in)
    if(t_in(k) < 10)
           T_in(k) = t_in(k);
    else
           T_in(k) = sin(t_in(k));
    end
end


% Now we assign this to the input signal
simT = [t_in T_in];
